apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-provider
spec:
  selector:
    matchLabels:
      app: token-provider
  replicas: 1
  template:
    metadata:
      labels:
        app: token-provider
    spec:
      containers:
        - name: token-provider
          image: jfrhudson/token-provider:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: token-provider
  name: token-provider
  namespace: jefferson023
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: token-provider
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-music
spec:
  selector:
    matchLabels:
      app: my-music
  replicas: 1
  template:
    metadata:
      labels:
        app: my-music
    spec:
      containers:
        - name: my-music
          image: jfrhudson/my-music:1.0
          imagePullPolicy: Always
          env:
            - name: TOKEN_PROVIDER_URL
              value: http://token-provider:8081/
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-music
  name: my-music
  namespace: jefferson023
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
      app: my-music
  sessionAffinity: None
  type: LoadBalancer